### ISSUE TITLE
Generating vmap from multilingual corpus

### ISSUE THREAD

**Issue by santha96** [OpenNMT/papers#4]
Hi,
I m trying to improve the inference time of the multilingual model. Is there any way to generate a VMAP from "one to many" multilingual corpus ?

**Comment by guillaumekln** [comment]
Hi,

Yes, you can run the VMAP build scripts on the same multilingual data that you used for training the model. If you did not train the model yourself, you would need to rebuild a representative tokenized dataset of these multilingual data.

**Comment by santha96** [comment]
Thanks a lot, @guillaumekln.
